requires 'perl' => '5.006';
requires 'Carp';
requires 'Encode';
requires 'Fcntl';
requires 'IO::Handle';
requires 'Moo' => '2.000002';
requires 'namespace::clean';
requires 'Role::EventEmitter' => '0.001';
test_requires 'File::Spec::Functions';
test_requires 'File::Temp';
test_requires 'Test::More' => '0.88';
